added gh action config files for 2.7 automation (#1010)
Signed-off-by: dislbenn <dbennett@redhat.com>

diff --git a/.github/workflows/regenerate-operator-bundles-2.7.yml b/.github/workflows/regenerate-operator-bundles-2.7.yml
--- a/.github/workflows/regenerate-operator-bundles-2.7.yml
+++ b/.github/workflows/regenerate-operator-bundles-2.7.yml
@@ -1,6 +1,6 @@
 # This is a basic workflow to help you get started with Actions
 
-name: Regenerate 2.3 Operator Bundles
+name: Regenerate 2.7 Operator Bundles
 
 # Controls when the action will run. 
 on:
@@ -27,31 +27,31 @@ jobs:
       - uses: actions/checkout@v2
         with:
           token: ${{ secrets.BACKPLANE_TOKEN }}
-          ref: backplane-2.3
+          ref: backplane-2.7
       - name: Set up Python ${{ matrix.python-version }}
         uses: actions/setup-python@v2
         with:
           python-version: ${{ matrix.python-version }}
 
       # Runs a set of commands using the runners shell
-      - name: Lint Operator Bundles
-        id: lint_bundle
-        run: |
-          make lint-operator-bundles
-          exit_code=$?
-          if [ $exit_code -ne 0 ]; then
-            echo "Lint Operator Bundles step failed with exit code $exit_code"
-            exit $exit_code
-          fi
+      # - name: Lint Operator Bundles
+      #   id: lint_bundle
+      #   run: |
+      #     make lint-operator-bundles
+      #     exit_code=$?
+      #     if [ $exit_code -ne 0 ]; then
+      #       echo "Lint Operator Bundles step failed with exit code $exit_code"
+      #       exit $exit_code
+      #     fi
           
       # Runs a set of commands using the runners shell
-      - name: Regenerate Operator Bundles
-        id: generate_bundle
+      - name: Regenerate Operator Charts From Bundles
+        id: generate_charts_from_bundles
         run: |
-          make regenerate-operator-bundles
+          make regenerate-charts-from-bundles
           exit_code=$?
           if [ $exit_code -ne 0 ]; then
-            echo "Regenerate Operator Bundles step failed with exit code $exit_code"
+            echo "Regenerate Operator Charts From Bundles step failed with exit code $exit_code"
             exit $exit_code
           fi
 
@@ -73,9 +73,9 @@ jobs:
         uses: peter-evans/create-pull-request@v3
         with:
           signoff: true
-          branch: "regenerate-operator-bundles-2.3"
+          branch: "regenerate-operator-bundles-2.7"
           delete-branch: true
-          title: "Operator Bundle Update [2.3]"
+          title: "Operator Bundle Update [2.7]"
           committer: GitHub <noreply@github.com>
           author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
           labels: |
