updated regenerate-bundles make command
Signed-off-by: Disaiah Bennett <dbennett@redhat.com>

diff --git a/.github/workflows/regenerate-operator-bundles-2.6.yml b/.github/workflows/regenerate-operator-bundles-2.6.yml
--- a/.github/workflows/regenerate-operator-bundles-2.6.yml
+++ b/.github/workflows/regenerate-operator-bundles-2.6.yml
@@ -34,15 +34,15 @@ jobs:
           python-version: ${{ matrix.python-version }}
 
       # Runs a set of commands using the runners shell
-      - name: Lint Operator Bundles
-        id: lint_bundle
-        run: |
-          make lint-operator-bundles
-          exit_code=$?
-          if [ $exit_code -ne 0 ]; then
-            echo "Lint Operator Bundles step failed with exit code $exit_code"
-            exit $exit_code
-          fi
+      # - name: Lint Operator Bundles
+      #   id: lint_bundle
+      #   run: |
+      #     make lint-operator-bundles
+      #     exit_code=$?
+      #     if [ $exit_code -ne 0 ]; then
+      #       echo "Lint Operator Bundles step failed with exit code $exit_code"
+      #       exit $exit_code
+      #     fi
           
       # Runs a set of commands using the runners shell
       - name: Regenerate Operator Charts From Bundles
diff --git a/.github/workflows/regenerate-operator-bundles.yml b/.github/workflows/regenerate-operator-bundles.yml
--- a/.github/workflows/regenerate-operator-bundles.yml
+++ b/.github/workflows/regenerate-operator-bundles.yml
@@ -38,13 +38,23 @@ jobs:
       # - name: Lint Operator Bundles
       #   id: lint_bundle
       #   run: |
-      #     make lint-operator-bundles    
+      #     make lint-operator-bundles
+      #     exit_code=$?
+      #     if [ $exit_code -ne 0 ]; then
+      #       echo "Lint Operator Bundles step failed with exit code $exit_code"
+      #       exit $exit_code
+      #     fi
 
       # Runs a set of commands using the runners shell
-      - name: Regenerate Operator Bundles
-        id: generate_bundle
+      - name: Regenerate Operator Charts From Bundles
+        id: generate_charts_from_bundles
         run: |
-          make regenerate-operator-bundles
+          make regenerate-charts-from-bundles
+          exit_code=$?
+          if [ $exit_code -ne 0 ]; then
+            echo "Regenerate Operator Charts From Bundles step failed with exit code $exit_code"
+            exit $exit_code
+          fi
 
       - name: Send Slack Message on Failure
         if: ${{ failure() }}
